### ISSUE TITLE
Add Comma

### ISSUE THREAD

**Issue by mhcrocker** [NSCC-ITC-Winter2024-ICOM5015-700-MCr/icom5015-fs-2024#23]
In the paragraph in the "Description" section of the `README.md` file add a comma after "... veterinary care" and before "and logging...".

**Comment by Zhengyq987** [comment]
I would like to work on it please!

**Comment by Zhengyq987** [comment]
![image](https://github.com/NSCC-ITC-Winter2024-ICOM5015-700-MCr/icom5015-fs-2024/assets/144251985/d353d2d8-3f7e-47ef-95db-5750370d82e4)

**Comment by Zhengyq987** [comment]
I would like to work on this please!
